/*const data = [
    {
        id: "101",
        comunidad: "Itziar",
        pueblo: "Lorem Ipsum",
        ciudad: "Clorinda",
        productos:  [ 
            {   
                nombreEspañol: "Canastas",
                nombreWichi: "Taosj",
                cantidad: "12",
                descrpcion: " It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
                img: "./images/productos/almohadones.jpg",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "maceta",
                nombreWichi: "Texcoas",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/productos/azucarera.jpg",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {  
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
          ],
    },
    {
        id: "102",
        comunidad: "Gornim",
        pueblo: "Julio Verne",
        ciudad: "Formosa",
        productos:  [ 
            {   
                nombreEspañol: "Canastas",
                nombreWichi: "Taosj",
                cantidad: "12",
                descrpcion: " It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
                img: "./images/productos/almohadones.jpg",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "maceta",
                nombreWichi: "Texcoas",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "92",
                mediasAncho: "43", 
                medidasLargo: "23",
            },
            {  
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
          ],
    },
    {
        id: "103",
        comunidad: "Ispur",
        pueblo: "Ada Lovelace",
        ciudad: "Gato Colorado",
        productos:  [ 
            {   
                nombreEspañol: "Canastas",
                nombreWichi: "Taosj",
                cantidad: "12",
                descrpcion: " It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
                img: "./images/productos/almohadones.jpg",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "maceta",
                nombreWichi: "Texcoas",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {  
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
          ],
    },
    {
        id: "104",
        comunidad: "Itziar",
        pueblo: "Ipsum Lorem",
        ciudad: "Lucio V. Mansilla",
        productos:  [ 
            {   
                nombreEspañol: "Canastas",
                nombreWichi: "Taosj",
                cantidad: "12",
                descrpcion: " It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", 
                img: "./images/productos/almohadones.jpg",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "maceta",
                nombreWichi: "Texcoas",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {   
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
            {  
                nombreEspañol: "canastas",
                nombreWichi: "taosj",
                cantidad: "12",
                descrpcion: "dfdfisdijfsdfijsidjid", 
                img: "./images/equipo/1ALourdesLopez.png",
                medidasAlto: "12",
                mediasAncho: "40", 
                medidasLargo: "23",
            },
          ],
    },
]
export default data;*/